
title: My Resume
url: 'https://github.com/henrikkitenkanen'
baseurl: '/cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2  # light green
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6  # grey

#Profile information
name: Henrikki Tenkanen
tagline: Researcher <br> GeoData scientist <br> Full Stack Developer
pic: Henkka.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: henrikki.tenkanen@hels***.fi
phone: +358504484436
website: henrikkitenkanen.github.io #do not add http://
linkedin: henrikki-tenkanen
github: htenkanen
twitter: '@tenkahen'

#Update all the sections by editing the files inside _includes folder.
